"""
TWINFORGE — Pydantic v2 schemas for all inter-agent message contracts.
Every message crossing an agent boundary MUST conform to one of these schemas.
"""
from __future__ import annotations
from datetime import datetime
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field, field_validator


# ═══════════════════════════════════════════════════════════
# ENUMS
# ═══════════════════════════════════════════════════════════

class Intent(str, Enum):
    CREATE_TWIN = "CREATE_TWIN"
    QUERY_TWIN = "QUERY_TWIN"
    GET_KPI = "GET_KPI"
    LIST_TWINS = "LIST_TWINS"
    GET_ALERTS = "GET_ALERTS"
    DELETE_TWIN = "DELETE_TWIN"
    UPDATE_TWIN = "UPDATE_TWIN"
    GENERAL_QUERY = "GENERAL_QUERY"
    UNKNOWN = "UNKNOWN"


class TwinLevel(str, Enum):
    COMPONENT = "Component"
    ASSET = "Asset"
    SYSTEM = "System"
    PROCESS = "Process"


class AlertSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


# ═══════════════════════════════════════════════════════════
# AGENT 1 — CONVERSATION AGENT SCHEMAS
# ═══════════════════════════════════════════════════════════

class UserInput(BaseModel):
    """Schema IN for Agent 1: raw user message."""
    user_message: str = Field(..., max_length=4096)
    session_id: str = Field(default="default")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class IntentResult(BaseModel):
    """Schema OUT from Agent 1 → Agent 2: classified intent."""
    intent: Intent
    entities: dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(ge=0.0, le=1.0)
    session_id: str = Field(default="default")
    raw_message: str = Field(default="")


# ═══════════════════════════════════════════════════════════
# AGENT 3 — DATA & IoT AGENT SCHEMAS
# ═══════════════════════════════════════════════════════════

class DataRequest(BaseModel):
    """Schema IN for Agent 3: request sensor data."""
    data_request: str = Field(default="live_sensors")
    asset_id: str
    time_range: dict[str, Any] = Field(default_factory=lambda: {"last": "1h"})


class SensorReading(BaseModel):
    """A single sensor reading."""
    sensor_id: str
    value: float
    unit: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class Anomaly(BaseModel):
    """Detected anomaly in sensor data."""
    sensor_id: str
    value: float
    threshold: float
    severity: AlertSeverity
    message: str


class DataResponse(BaseModel):
    """Schema OUT from Agent 3 → Agent 2: validated sensor data."""
    asset_id: str
    sensor_data: dict[str, Any] = Field(default_factory=dict)
    readings: list[SensorReading] = Field(default_factory=list)
    validated: bool = True
    anomalies: list[Anomaly] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


# ═══════════════════════════════════════════════════════════
# AGENT 2 — TWIN ORCHESTRATOR SCHEMAS
# ═══════════════════════════════════════════════════════════

class KPIData(BaseModel):
    """Key Performance Indicators for a digital twin."""
    availability: float = Field(ge=0.0, le=100.0, default=0.0)
    performance: float = Field(ge=0.0, le=100.0, default=0.0)
    quality: float = Field(ge=0.0, le=100.0, default=0.0)
    oee: float = Field(ge=0.0, le=100.0, default=0.0)
    energy_consumption_kwh: float = Field(ge=0.0, default=0.0)
    cycle_time_seconds: float = Field(ge=0.0, default=0.0)
    
    @field_validator("oee", mode="before")
    @classmethod
    def clamp_oee(cls, v):
        return min(max(float(v), 0.0), 100.0)


class Alert(BaseModel):
    """An alert generated by the twin orchestrator."""
    alert_id: str
    asset_id: str
    severity: AlertSeverity
    message: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    resolved: bool = False


class TwinResult(BaseModel):
    """Schema OUT from Agent 2 → Agent 1: twin operation result."""
    twin_id: str
    twin_level: TwinLevel
    kpis: KPIData = Field(default_factory=KPIData)
    alerts: list[Alert] = Field(default_factory=list)
    aas_reference: str = Field(default="")
    explanation: str = Field(default="")
    reasoning_trace: list[str] = Field(default_factory=list)
    components: list[dict[str, Any]] = Field(default_factory=list)


# ═══════════════════════════════════════════════════════════
# OBSERVABILITY — AGENT ACTION LOG
# ═══════════════════════════════════════════════════════════

class AgentAction(BaseModel):
    """Every agent action emits this log entry."""
    agent_id: str
    action: str
    tool_used: str = Field(default="none")
    input_hash: str = Field(default="")
    output_hash: str = Field(default="")
    duration_ms: float = Field(default=0.0)
    success: bool = True
    reasoning_trace: str = Field(default="")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    error: Optional[str] = None


# ═══════════════════════════════════════════════════════════
# TWIN STORE ENTRY
# ═══════════════════════════════════════════════════════════

class TwinEntry(BaseModel):
    """A persisted digital twin in the store."""
    twin_id: str
    twin_level: TwinLevel
    asset_type: str = Field(default="Generic")
    name: str = Field(default="")
    floor: str = Field(default="")
    line: str = Field(default="")
    protocol: str = Field(default="OPC-UA")
    energy_kwh: float = Field(ge=0.0, default=0.0)
    components: list[dict[str, Any]] = Field(default_factory=list)
    kpis: KPIData = Field(default_factory=KPIData)
    alerts: list[Alert] = Field(default_factory=list)
    aas_reference: str = Field(default="")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    session_id: str = Field(default="default")
    metadata: dict[str, Any] = Field(default_factory=dict)
